import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    marginHorizontal: 0,
    flexDirection: 'column',
  },
  uperView: {
    flex: 1,
    flexDirection: 'column',
    alignContent: 'center',
    justifyContent: 'center',
    alignItems: 'center',
  },
  button: {
    backgroundColor: 'white',

    borderColor: 'black',
    borderWidth: 2,
    borderRadius: 8,
  },
  secondView: {
    backgroundColor: 'white',
    width: 50,
    height: 50,
    borderColor: 'black',
    borderWidth: 2,
    borderRadius: 8,
    marginVertical: 8,
  },
  horiView: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
  },
  otherButton: {
    backgroundColor: 'white',

    borderColor: 'black',
    borderWidth: 2,
    borderRadius: 8,
  },
  otherView: {
    backgroundColor: 'white',
    width: 50,
    height: 50,
    borderColor: 'black',
    borderWidth: 2,
    borderRadius: 8,
    marginHorizontal: 8,
  },
  textMiddle: {alignSelf: 'center', marginVertical: 8},
  text: {flexDirection: 'row', alignItems: 'center'},
  centeredView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 22,
  },
  InputTextStyle: {
    height: 45,
    fontSize: 14,
    marginHorizontal: 16,
    borderColor: 'black',
    borderRadius: 10,
    borderWidth: 1,
    textAlign: 'center',
    marginBottom: 30,
  },
  loginScreenButton: {
    marginRight: 40,
    marginLeft: 40,
    marginTop: 10,
    paddingTop: 10,
    paddingBottom: 10,
    backgroundColor: '#1E6738',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#fff',
  },
  loginText: {
    color: '#fff',
    textAlign: 'center',
    paddingLeft: 10,
    paddingRight: 10,
  },
  hintText: {
    color: 'black',
    textAlign: 'center',
    paddingLeft: 10,
    paddingRight: 10,
  },
  modalView: {
    backgroundColor: '#0000009c',
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  subModalView: {
    width: '80%',
    height: '50%',
    backgroundColor: 'white',
    justifyContent: 'center',
  },
});
